//! Build-time orchestration for the embedded `rstudiocli` R package.
//!
//! Two jobs:
//!
//! 1. Enforce that the Cargo crate version and the R package
//!    `DESCRIPTION::Version` are in lock-step. A drift between the two
//!    would mean a binary that ships an R package claiming to be a
//!    different version — silent footgun. Compilation fails loudly
//!    instead.
//!
//! 2. Produce the source tarball of the R package in `OUT_DIR` so
//!    `include_bytes!` can embed it in the binary. We prefer
//!    `R CMD build` (which strips junk, validates structure, and is
//!    what an R user would do) and fall back to plain `tar` when R
//!    is not installed on the build host — useful for first-time
//!    contributors and for cross-compilation environments that don't
//!    necessarily have R.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));
    let r_pkg_dir = manifest_dir.join("r-package");

    // Rebuild whenever any R-package source changes.
    println!("cargo:rerun-if-changed={}", r_pkg_dir.display());
    println!("cargo:rerun-if-changed=Cargo.toml");

    let cargo_version = env!("CARGO_PKG_VERSION");
    let desc_version = read_description_version(&r_pkg_dir.join("DESCRIPTION"))
        .expect("failed to read r-package/DESCRIPTION Version field");
    assert_eq!(
        cargo_version, desc_version,
        "version mismatch: Cargo.toml = {cargo_version}, r-package/DESCRIPTION = {desc_version}. \
         Bump both, or run `cargo run --bin sync-version` (if available)."
    );

    // Compute a stable build-id from the contents of `r-package/` so the
    // runtime installer can detect any change to the embedded package —
    // even within the same nominal version. This solves the dev-loop
    // case where r-package/ is iterated without bumping Cargo version:
    // the disk install may match the version string yet contain
    // different exports.
    let build_id = compute_build_id(&r_pkg_dir);

    // Stage a copy of the R package with an auto-generated R/zzz.R that
    // exposes the build-id to runtime checks via `.rstudiocli_build_id()`.
    let staged = out_dir.join("r-package-with-buildid");
    let _ = fs::remove_dir_all(&staged);
    copy_dir_recursive(&r_pkg_dir, &staged).expect("stage r-package");
    fs::write(
        staged.join("R").join("zzz-build-id.R"),
        format!(
            "# Auto-generated by build.rs — DO NOT EDIT.\n\
             # Build-id derived from a hash of the r-package/ source tree.\n\
             # The CLI uses this to detect mid-version changes and force a\n\
             # reinstall when the embedded package differs from the loaded one.\n\
             .rstudiocli_build_id <- function() {build_id_q}\n",
            build_id_q = r_string_lit(&build_id),
        ),
    )
    .expect("write zzz-build-id.R");

    let tarball = out_dir.join("r-package.tar.gz");

    let used_r = if which_r().is_some() {
        run_r_cmd_build(&staged, &out_dir, &tarball, cargo_version)
    } else {
        false
    };

    if !used_r {
        // Fallback: build a plain tarball by hand. Slightly less polished
        // (doesn't strip backup files etc.) but a valid R source package
        // that install.packages(type = "source") accepts.
        fallback_tar_build(&staged, &tarball);
    }

    assert!(
        tarball.exists(),
        "build.rs failed to produce {}",
        tarball.display()
    );

    fs::write(out_dir.join("r-package-build-id.txt"), &build_id)
        .expect("write r-package-build-id.txt");
}

fn compute_build_id(r_pkg_dir: &Path) -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    // Hash every source file under r-package/ (sorted by path for
    // determinism). Excludes generated artifacts that R CMD build would
    // strip anyway.
    let mut paths = Vec::new();
    collect_files(r_pkg_dir, &mut paths);
    paths.sort();
    let mut hasher = DefaultHasher::new();
    for p in paths {
        if let Ok(rel) = p.strip_prefix(r_pkg_dir) {
            rel.to_string_lossy().hash(&mut hasher);
        }
        if let Ok(bytes) = fs::read(&p) {
            bytes.hash(&mut hasher);
        }
    }
    format!("{:016x}", hasher.finish())
}

fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let p = entry.path();
        if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            collect_files(&p, out);
        } else {
            out.push(p);
        }
    }
}

/// Quote a string as an R character literal (double-quoted, with
/// backslash-escaped quotes and backslashes).
fn r_string_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' | '\\' => {
                out.push('\\');
                out.push(ch);
            }
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn read_description_version(path: &Path) -> Option<String> {
    let raw = fs::read_to_string(path).ok()?;
    for line in raw.lines() {
        if let Some(rest) = line.strip_prefix("Version:") {
            return Some(rest.trim().to_string());
        }
    }
    None
}

fn which_r() -> Option<PathBuf> {
    Command::new("R")
        .arg("--version")
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|_| PathBuf::from("R"))
}

/// Run `R CMD build r-package` from `out_dir` and move the produced
/// tarball to `target`. Returns true on success.
fn run_r_cmd_build(r_pkg_dir: &Path, out_dir: &Path, target: &Path, version: &str) -> bool {
    let status = Command::new("R")
        .args(["CMD", "build", "--no-manual", "--no-build-vignettes"])
        .arg(r_pkg_dir)
        .current_dir(out_dir)
        .status();
    let ok = matches!(status, Ok(s) if s.success());
    if !ok {
        return false;
    }
    // R CMD build creates rstudiocli_<version>.tar.gz in CWD.
    let produced = out_dir.join(format!("rstudiocli_{version}.tar.gz"));
    if !produced.exists() {
        return false;
    }
    // Move to the canonical filename so include_bytes! has a fixed path.
    let _ = fs::rename(&produced, target);
    target.exists()
}

/// Plain-tar fallback when R isn't available on the build host. Builds
/// `rstudiocli/...` rooted at the package name, which is what
/// `install.packages(..., type = "source")` expects from a tarball.
fn fallback_tar_build(r_pkg_dir: &Path, target: &Path) {
    let parent = r_pkg_dir
        .parent()
        .expect("r-package must have a parent directory");
    // Stage the package under its canonical name ("rstudiocli"), not
    // "r-package", so tar entries are prefixed correctly.
    let stage = parent.join("target").join("r-package-stage");
    let _ = fs::remove_dir_all(&stage);
    fs::create_dir_all(&stage).expect("create stage dir");
    let staged_pkg = stage.join("rstudiocli");
    copy_dir_recursive(r_pkg_dir, &staged_pkg).expect("stage r-package");

    let status = Command::new("tar")
        .args(["-czf"])
        .arg(target)
        .arg("-C")
        .arg(&stage)
        .arg("rstudiocli")
        .status()
        .expect("invoke tar");
    assert!(status.success(), "tar fallback failed");

    let _ = fs::remove_dir_all(&stage);
}

fn copy_dir_recursive(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let name = entry.file_name();
        let src_path = entry.path();
        let dst_path = dst.join(&name);
        if entry.file_type()?.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}
