//! Embedded `rstudiocli` R package: ship + auto-install.
//!
//! The package source tarball is embedded at compile time via
//! `include_bytes!` (see `build.rs` for how the tarball is produced).
//! On first contact with an rsession we ensure a matching version is
//! installed; if not, we install it silently from the embedded bytes.
//!
//! Policy: install on first use, no confirmation. An rstudio-cli user
//! has already opted in to a binary that drives their R session — a
//! pure-R package installed in their user library is strictly less
//! invasive than the alternatives we considered (injecting an
//! environment via `attach()`, sourcing code into `.GlobalEnv`, etc.).
//!
//! The check is memoised per-process: a single `rstudio` invocation
//! pays at most one round-trip with rsession to verify the version,
//! plus the one-shot install on a clean session.

use std::path::PathBuf;
use std::sync::OnceLock;

use crate::error::CliError;
use crate::r_eval;
use crate::rpc::RpcClient;

/// Embedded source tarball of the `rstudiocli` R package. Built
/// by `build.rs` (either via `R CMD build` or a tar fallback) and
/// dropped into `OUT_DIR/r-package.tar.gz`.
const R_PACKAGE_TARBALL: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/r-package.tar.gz"));

/// The version of the R package that ships with this binary. Verified
/// against `Cargo.toml` at compile-time (build.rs) so we don't need a
/// separate constant: they're guaranteed equal.
const R_PACKAGE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Content-hash of the R package sources, baked in at build time. The
/// package R code exposes a matching `.rstudiocli_build_id()` function
/// (generated by build.rs). The runtime check compares both: any
/// mismatch — including within the same version, e.g. during dev — triggers
/// a fresh install. This is what makes the auto-install reliable when the
/// package iterates faster than the Cargo version number.
const R_PACKAGE_BUILD_ID: &str = include_str!(concat!(env!("OUT_DIR"), "/r-package-build-id.txt"));

const R_PACKAGE_NAME: &str = "rstudiocli";

/// Memoise "we already ensured installation in this process" so that
/// chains of CLI invocations or MCP tool calls don't repeat the
/// version-check round-trip.
static ENSURED: OnceLock<()> = OnceLock::new();

/// Ensure the rsession has `rstudiocli` installed at the version
/// shipped with this binary. Silent on success; returns an error only
/// if both the version check and the install fail.
///
/// Safe to call from the hot path: short-circuits after the first
/// successful call within a single process.
///
/// Recursion safety: this function itself calls `rpc.rpc("execute_r_code", ...)`,
/// so if callers also hook into the RPC layer (e.g. via a check at
/// the top of `RpcClient::rpc`), they must ensure those nested calls
/// see `ENSURED` already set. We set it **before** running the
/// `execute_r_code` probe so that re-entrancy short-circuits at the
/// top of this function. The cost: a failed install/check leaves the
/// process in a "we think it's done" state for the rest of its life —
/// acceptable, since both check and install raise `CliError` on
/// failure that the caller propagates.
pub fn ensure_installed(rpc: &RpcClient<'_>) -> Result<(), CliError> {
    if ENSURED.get().is_some() {
        return Ok(());
    }
    // Set the marker FIRST so the nested `execute_r_code` inside
    // check_installed / install_from_embedded short-circuits when they
    // re-enter the RPC layer (which now also calls ensure_installed).
    let _ = ENSURED.set(());

    let status = check_installed(rpc)?;
    if matches!(status, InstallStatus::CurrentVersion) {
        return Ok(());
    }
    install_from_embedded(rpc)?;
    Ok(())
}

#[derive(Debug, PartialEq, Eq)]
enum InstallStatus {
    /// Already installed at the expected version; nothing to do.
    CurrentVersion,
    /// Either not installed, or installed at a different version.
    NeedsInstall,
}

fn check_installed(rpc: &RpcClient<'_>) -> Result<InstallStatus, CliError> {
    // Two-axis probe to keep the binary and rsession in sync:
    //
    // 1. **Version** (`packageVersion(...)`): does disk match the
    //    binary's `Cargo.toml::version`? Detects across-version drift.
    // 2. **Build-id**: a hash of the package source tree baked in at
    //    compile time (see `R_PACKAGE_BUILD_ID`) and exposed by the
    //    R package as `rstudiocli:::.rstudiocli_build_id()`.
    //    Detects within-version drift — typical during development,
    //    when the package iterates faster than the Cargo version.
    //
    // We also check the loaded namespace's build-id when applicable,
    // because a stale namespace in rsession would shadow the disk
    // install. `install_from_embedded` then `unloadNamespace()`s the
    // stale one so the freshly-installed code takes over.
    let probe = format!(
        "local({{\n  \
            target_ver <- {ver}\n  \
            target_bid <- {bid}\n  \
            disk_ver <- tryCatch(as.character(utils::packageVersion({pkg})),\n                                  \
                                 error = function(e) NULL)\n  \
            if (is.null(disk_ver)) {{ cat('missing'); return(invisible()) }}\n  \
            if (disk_ver != target_ver) {{ cat('disk_version_mismatch:', disk_ver); return(invisible()) }}\n  \
            disk_bid <- tryCatch(\n               \
                getFromNamespace('.rstudiocli_build_id', {pkg})(),\n               \
                error = function(e) '<missing>')\n  \
            if (disk_bid != target_bid) {{ cat('build_id_mismatch:', disk_bid); return(invisible()) }}\n  \
            cat('ok')\n  \
         }})",
        pkg = r_quote(R_PACKAGE_NAME),
        ver = r_quote(R_PACKAGE_VERSION),
        bid = r_quote(R_PACKAGE_BUILD_ID.trim()),
    );
    let raw = r_eval::run(rpc, &probe)?;
    let trimmed = raw.trim();
    if trimmed == "ok" {
        Ok(InstallStatus::CurrentVersion)
    } else {
        Ok(InstallStatus::NeedsInstall)
    }
}

fn install_from_embedded(rpc: &RpcClient<'_>) -> Result<(), CliError> {
    // The CLI and rsession share a filesystem (Desktop, or Server on the same
    // host). Write the embedded tarball to a unique path under the user's
    // tempdir; both processes resolve it identically.
    let tmp = tempfile::Builder::new()
        .prefix("rstudiocli-")
        .suffix(".tar.gz")
        .tempfile()
        .map_err(|e| CliError::internal(format!("r_package: tempfile: {e}")))?;
    let path_for_writer: PathBuf = tmp
        .into_temp_path()
        .keep()
        .map_err(|e| CliError::internal(format!("r_package: persist tempfile: {e}")))?;
    let path_str = path_for_writer.to_string_lossy().into_owned();

    std::fs::write(&path_for_writer, R_PACKAGE_TARBALL)
        .map_err(|e| CliError::internal(format!("r_package: write tarball: {e}")))?;

    // install.packages with repos = NULL and type = "source" installs
    // from a local tarball. We deliberately let R pick the user library;
    // overriding lib= here would be surprising for the user.
    //
    // After install, if the package was already loaded with a stale
    // version (common during development), the namespace must be
    // unloaded so `pkg::fn` calls resolve against the freshly-installed
    // version rather than the in-memory one. We do it inside the same
    // R call so it stays atomic from the agent's perspective.
    // utils::install.packages() doesn't stop() on failure — it emits a
    // warning and returns NULL. We wrap the call so that any warning
    // raises an error visible to the CLI side, plus a final
    // requireNamespace() check confirms the install actually landed.
    let install_code = format!(
        "{{\n  \
           res <- withCallingHandlers(\n    \
             tryCatch({{\n      \
               utils::install.packages({tarball}, repos = NULL, type = 'source', quiet = TRUE)\n      \
               if ({pkg} %in% loadedNamespaces()) tryCatch(unloadNamespace({pkg}), error = function(e) {{}})\n      \
               TRUE\n    \
             }}, error = function(e) {{ conditionMessage(e) }}),\n    \
             warning = function(w) {{ stop(\"install warning: \", conditionMessage(w), call. = FALSE) }},\n    \
             message = function(m) {{ invokeRestart('muffleMessage') }}\n  \
           )\n  \
           if (!isTRUE(res)) stop(\"install.packages returned non-TRUE: \", res, call. = FALSE)\n  \
           if (!requireNamespace({pkg}, quietly = TRUE)) stop(\"install.packages reported success but {pkg} still not findable\", call. = FALSE)\n\
         }}",
        pkg = r_quote(R_PACKAGE_NAME),
        tarball = r_quote(&path_str)
    );
    r_eval::run_silent(rpc, &install_code).map_err(|e| {
        CliError::internal(format!(
            "r_package: failed to install {}: {e}",
            R_PACKAGE_NAME
        ))
    })?;

    let _ = std::fs::remove_file(&path_for_writer);
    Ok(())
}

/// R-style string literal with single-quote escaping. Adequate for our
/// use cases (package names, version strings, filesystem paths).
fn r_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' || ch == '\\' {
            out.push('\\');
        }
        out.push(ch);
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_tarball_is_nonempty() {
        // Sanity: build.rs really did put bytes here.
        assert!(!R_PACKAGE_TARBALL.is_empty());
        // gzip magic
        assert_eq!(&R_PACKAGE_TARBALL[..2], &[0x1f, 0x8b]);
    }

    #[test]
    fn r_quote_escapes_quotes_and_backslashes() {
        assert_eq!(r_quote("hello"), "'hello'");
        assert_eq!(r_quote("it's"), r"'it\'s'");
        assert_eq!(r_quote(r"\path"), r"'\\path'");
    }

    #[test]
    fn version_constant_matches_cargo() {
        assert_eq!(R_PACKAGE_VERSION, env!("CARGO_PKG_VERSION"));
    }
}
